package Dashboard;

import AdminPages.*;
import RegisterPages.*;
import java.awt.BorderLayout;
import javax.swing.Box;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        appbut = new javax.swing.JButton();
        jobbutton = new javax.swing.JButton();
        compbutton = new javax.swing.JButton();
        clgbutton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homemenu = new javax.swing.JMenu();
        compmenu = new javax.swing.JMenu();
        jobsmenu = new javax.swing.JMenu();
        addnew = new javax.swing.JMenu();
        addstud = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        addjob = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        addcomp = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        addcollege = new javax.swing.JMenuItem();
        reports = new javax.swing.JMenu();
        changepass = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1061, 882));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(51, 0, 153));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("CAMPUS RECRUITMENT SYSTEM");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("A  complete  solution  for  managing  Vacancies , Placements , Colleges  and  Students");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 856, 26));

        jLabel4.setText("Welcome Admin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 140));

        jButton1.setBackground(new java.awt.Color(51, 0, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LogOut");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 590, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("WELCOME TO CAMPUS RECRUITMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1061, 63));

        appbut.setBackground(new java.awt.Color(51, 0, 153));
        appbut.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        appbut.setForeground(new java.awt.Color(255, 255, 255));
        appbut.setText("Add Applicant");
        appbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appbutActionPerformed(evt);
            }
        });
        getContentPane().add(appbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 590, 60));

        jobbutton.setBackground(new java.awt.Color(51, 0, 153));
        jobbutton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jobbutton.setForeground(new java.awt.Color(255, 255, 255));
        jobbutton.setText("Add Job");
        jobbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(jobbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 590, 60));

        compbutton.setBackground(new java.awt.Color(51, 0, 153));
        compbutton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        compbutton.setForeground(new java.awt.Color(255, 255, 255));
        compbutton.setText("Add Company");
        compbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(compbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 590, 60));

        clgbutton.setBackground(new java.awt.Color(51, 0, 153));
        clgbutton.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        clgbutton.setForeground(new java.awt.Color(255, 255, 255));
        clgbutton.setText("Add Colleges");
        clgbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clgbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clgbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 590, 60));

        jButton6.setBackground(new java.awt.Color(51, 0, 153));
        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Job Applications");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 590, 60));

        jButton7.setBackground(new java.awt.Color(51, 0, 153));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Change Password");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 590, 60));

        jLabel3.setBackground(new java.awt.Color(51, 0, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dashboard/po.jpeg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 520, 600));

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1037, 47));
        jMenuBar1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jMenuBar1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        homemenu.setText("         HOME         ");
        jMenuBar1.add(homemenu);

        compmenu.setText("      COMPANIES       ");
        compmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compmenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(compmenu);

        jobsmenu.setText("       ALL JOBS      ");
        jMenuBar1.add(jobsmenu);

        addnew.setText("      ADD NEW            ");

        addstud.setText("Add Student");
        addstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudActionPerformed(evt);
            }
        });
        addnew.add(addstud);
        addnew.add(jSeparator1);

        addjob.setText("Add Job");
        addjob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjobActionPerformed(evt);
            }
        });
        addnew.add(addjob);
        addnew.add(jSeparator2);

        addcomp.setText("Add Company");
        addcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcompActionPerformed(evt);
            }
        });
        addnew.add(addcomp);
        addnew.add(jSeparator3);

        addcollege.setText("Add College");
        addcollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcollegeActionPerformed(evt);
            }
        });
        addnew.add(addcollege);

        jMenuBar1.add(addnew);

        reports.setText("      REPORTS            ");
        jMenuBar1.add(reports);

        changepass.setText("       CHANGE PASSWORD");
        jMenuBar1.add(changepass);

        logout.setText("                LOGOUT             ");
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jMenuBar1CaretPositionChanged

    }//GEN-LAST:event_jMenuBar1CaretPositionChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudActionPerformed
        RegisterStudent rs=new RegisterStudent();  
        rs.setVisible(true);
       
    }//GEN-LAST:event_addstudActionPerformed

    private void addcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcompActionPerformed
        new RegisterCompany();
    }//GEN-LAST:event_addcompActionPerformed

    private void compbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compbuttonActionPerformed
        new RegisterCompany();
    }//GEN-LAST:event_compbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addjobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjobActionPerformed
       new AddJob().setVisible(true);
    }//GEN-LAST:event_addjobActionPerformed

    private void addcollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcollegeActionPerformed
       new CollegeForm().setVisible(true);
    }//GEN-LAST:event_addcollegeActionPerformed

    private void appbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appbutActionPerformed
        RegisterStudent rs=new RegisterStudent();  
        rs.setVisible(true);
    }//GEN-LAST:event_appbutActionPerformed

    private void jobbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobbuttonActionPerformed
        new AddJob().setVisible(true);
    }//GEN-LAST:event_jobbuttonActionPerformed

    private void clgbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clgbuttonActionPerformed
        new CollegeForm().setVisible(true);
    }//GEN-LAST:event_clgbuttonActionPerformed

    private void compmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compmenuActionPerformed
       
    }//GEN-LAST:event_compmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addcollege;
    private javax.swing.JMenuItem addcomp;
    private javax.swing.JMenuItem addjob;
    private javax.swing.JMenu addnew;
    private javax.swing.JMenuItem addstud;
    private javax.swing.JButton appbut;
    private javax.swing.JMenu changepass;
    private javax.swing.JButton clgbutton;
    private javax.swing.JButton compbutton;
    private javax.swing.JMenu compmenu;
    private javax.swing.JMenu homemenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jobbutton;
    private javax.swing.JMenu jobsmenu;
    private javax.swing.JMenu logout;
    private javax.swing.JMenu reports;
    // End of variables declaration//GEN-END:variables
}
